// Generated by scripts/geninstruments.py - do not edit by hand.
// Each entry carries the preset that makes the sound and how far the part
// is written above concert pitch, so picking an instrument both re-voices
// the channel and transposes the notation.
var INSTRUMENTS = [
 {
  "name": "Piano",
  "preset": "grand piano",
  "semitones": 0,
  "value": 128,
  "settings": {
   "type": "Picked String",
   "eqFilter": [
    {
     "type": "high-pass",
     "cutoffHz": 148.65,
     "linearGain": 0.7071
    },
    {
     "type": "peak",
     "cutoffHz": 1681.79,
     "linearGain": 4
    },
    {
     "type": "low-pass",
     "cutoffHz": 8000,
     "linearGain": 0.1768
    },
    {
     "type": "peak",
     "cutoffHz": 3363.59,
     "linearGain": 4
    },
    {
     "type": "peak",
     "cutoffHz": 2378.41,
     "linearGain": 0.25
    }
   ],
   "effects": [
    "note filter",
    "reverb"
   ],
   "noteFilter": [
    {
     "type": "low-pass",
     "cutoffHz": 4756.83,
     "linearGain": 0.3536
    },
    {
     "type": "high-pass",
     "cutoffHz": 125,
     "linearGain": 0.0884
    }
   ],
   "reverb": 67,
   "fadeInSeconds": 0,
   "fadeOutTicks": 48,
   "harmonics": [
    100,
    100,
    86,
    86,
    86,
    71,
    71,
    71,
    0,
    71,
    71,
    71,
    71,
    57,
    57,
    71,
    57,
    14,
    57,
    57,
    57,
    57,
    57,
    57,
    57,
    57,
    29,
    57
   ],
   "unison": "piano",
   "stringSustain": 86,
   "stringSustainType": "acoustic",
   "envelopes": [
    {
     "target": "noteFilterFreq",
     "envelope": "note size",
     "index": 0
    },
    {
     "target": "noteFilterFreq",
     "envelope": "twang 1",
     "index": 1
    },
    {
     "target": "noteFilterFreq",
     "envelope": "twang 1",
     "index": 1
    }
   ]
  }
 },
 {
  "name": "Flute",
  "preset": "flute",
  "semitones": 0,
  "value": 832,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 5657,
   "filterResonance": 14,
   "filterEnvelope": "steady",
   "vibrato": "none",
   "algorithm": "1←(2 3 4)",
   "feedbackType": "4⟲",
   "feedbackAmplitude": 7,
   "feedbackEnvelope": "decay 2",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 15,
     "envelope": "custom"
    },
    {
     "frequency": "2×",
     "amplitude": 4,
     "envelope": "steady"
    },
    {
     "frequency": "1×",
     "amplitude": 3,
     "envelope": "steady"
    },
    {
     "frequency": "~1×",
     "amplitude": 1,
     "envelope": "punch"
    }
   ]
  }
 },
 {
  "name": "Piccolo",
  "preset": "piccolo",
  "semitones": -12,
  "value": 836,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 5657,
   "filterResonance": 43,
   "filterEnvelope": "steady",
   "vibrato": "none",
   "algorithm": "1←3 2←4",
   "feedbackType": "4⟲",
   "feedbackAmplitude": 15,
   "feedbackEnvelope": "twang 1",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 15,
     "envelope": "custom"
    },
    {
     "frequency": "1×",
     "amplitude": 10,
     "envelope": "custom"
    },
    {
     "frequency": "~2×",
     "amplitude": 3,
     "envelope": "punch"
    },
    {
     "frequency": "~1×",
     "amplitude": 5,
     "envelope": "punch"
    }
   ]
  }
 },
 {
  "name": "Oboe",
  "preset": "oboe",
  "semitones": 0,
  "value": 774,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "cross fade",
   "chord": "harmony",
   "filterCutoffHz": 4000,
   "filterResonance": 14,
   "filterEnvelope": "swell 1",
   "vibrato": "none",
   "algorithm": "1 2←(3 4)",
   "feedbackType": "2⟲",
   "feedbackAmplitude": 2,
   "feedbackEnvelope": "tremolo5",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 7,
     "envelope": "custom"
    },
    {
     "frequency": "4×",
     "amplitude": 12,
     "envelope": "custom"
    },
    {
     "frequency": "1×",
     "amplitude": 6,
     "envelope": "steady"
    },
    {
     "frequency": "6×",
     "amplitude": 2,
     "envelope": "steady"
    }
   ]
  }
 },
 {
  "name": "Bassoon",
  "preset": "bassoon",
  "semitones": 0,
  "value": 776,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 707,
   "filterResonance": 57,
   "filterEnvelope": "steady",
   "vibrato": "none",
   "algorithm": "1←(2 3←4)",
   "feedbackType": "1⟲",
   "feedbackAmplitude": 2,
   "feedbackEnvelope": "steady",
   "operators": [
    {
     "frequency": "2×",
     "amplitude": 11,
     "envelope": "custom"
    },
    {
     "frequency": "1×",
     "amplitude": 6,
     "envelope": "steady"
    },
    {
     "frequency": "6×",
     "amplitude": 6,
     "envelope": "swell 1"
    },
    {
     "frequency": "1×",
     "amplitude": 0,
     "envelope": "steady"
    }
   ]
  }
 },
 {
  "name": "Clarinet (B♭)",
  "preset": "clarinet",
  "semitones": 2,
  "value": 777,
  "settings": {
   "type": "harmonics",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 1414,
   "filterResonance": 14,
   "filterEnvelope": "steady",
   "interval": "union",
   "vibrato": "none",
   "harmonics": [
    100,
    43,
    86,
    57,
    86,
    71,
    86,
    71,
    71,
    71,
    71,
    71,
    71,
    43,
    71,
    71,
    57,
    57,
    57,
    57,
    57,
    57,
    43,
    43,
    43,
    29,
    14,
    0
   ]
  }
 },
 {
  "name": "Soprano sax (B♭)",
  "preset": "soprano sax",
  "semitones": 2,
  "value": 768,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 2000,
   "filterResonance": 29,
   "filterEnvelope": "steady",
   "vibrato": "none",
   "algorithm": "1←2←3←4",
   "feedbackType": "4⟲",
   "feedbackAmplitude": 5,
   "feedbackEnvelope": "swell 1",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 13,
     "envelope": "custom"
    },
    {
     "frequency": "4×",
     "amplitude": 4,
     "envelope": "swell 1"
    },
    {
     "frequency": "1×",
     "amplitude": 7,
     "envelope": "steady"
    },
    {
     "frequency": "5×",
     "amplitude": 4,
     "envelope": "punch"
    }
   ]
  }
 },
 {
  "name": "Alto sax (E♭)",
  "preset": "alto sax",
  "semitones": 9,
  "value": 769,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 2000,
   "filterResonance": 43,
   "filterEnvelope": "steady",
   "vibrato": "none",
   "algorithm": "1←(2 3←4)",
   "feedbackType": "1⟲",
   "feedbackAmplitude": 4,
   "feedbackEnvelope": "punch",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 13,
     "envelope": "custom"
    },
    {
     "frequency": "1×",
     "amplitude": 6,
     "envelope": "steady"
    },
    {
     "frequency": "4×",
     "amplitude": 6,
     "envelope": "swell 1"
    },
    {
     "frequency": "1×",
     "amplitude": 12,
     "envelope": "steady"
    }
   ]
  }
 },
 {
  "name": "Tenor sax (B♭)",
  "preset": "tenor sax",
  "semitones": 14,
  "value": 770,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 2828,
   "filterResonance": 29,
   "filterEnvelope": "steady",
   "vibrato": "none",
   "algorithm": "1←2←3←4",
   "feedbackType": "1⟲",
   "feedbackAmplitude": 6,
   "feedbackEnvelope": "swell 1",
   "operators": [
    {
     "frequency": "2×",
     "amplitude": 12,
     "envelope": "custom"
    },
    {
     "frequency": "3×",
     "amplitude": 7,
     "envelope": "steady"
    },
    {
     "frequency": "1×",
     "amplitude": 3,
     "envelope": "steady"
    },
    {
     "frequency": "8×",
     "amplitude": 3,
     "envelope": "steady"
    }
   ]
  }
 },
 {
  "name": "Baritone sax (E♭)",
  "preset": "baritone sax",
  "semitones": 21,
  "value": 771,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 2828,
   "filterResonance": 0,
   "filterEnvelope": "steady",
   "vibrato": "none",
   "algorithm": "1←(2 3←4)",
   "feedbackType": "1⟲",
   "feedbackAmplitude": 2,
   "feedbackEnvelope": "swell 2",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 12,
     "envelope": "custom"
    },
    {
     "frequency": "8×",
     "amplitude": 4,
     "envelope": "steady"
    },
    {
     "frequency": "4×",
     "amplitude": 5,
     "envelope": "steady"
    },
    {
     "frequency": "1×",
     "amplitude": 4,
     "envelope": "punch"
    }
   ]
  }
 },
 {
  "name": "Trumpet (B♭)",
  "preset": "trumpet",
  "semitones": 2,
  "value": 704,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 2828,
   "filterResonance": 43,
   "filterEnvelope": "steady",
   "vibrato": "none",
   "algorithm": "1←(2 3 4)",
   "feedbackType": "1⟲",
   "feedbackAmplitude": 9,
   "feedbackEnvelope": "swell 1",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 14,
     "envelope": "custom"
    },
    {
     "frequency": "1×",
     "amplitude": 8,
     "envelope": "steady"
    },
    {
     "frequency": "1×",
     "amplitude": 5,
     "envelope": "flare 2"
    },
    {
     "frequency": "1×",
     "amplitude": 0,
     "envelope": "steady"
    }
   ]
  }
 },
 {
  "name": "Mellophone (F)",
  "preset": "mellophone",
  "semitones": 7,
  "value": 1088,
  "settings": {
   "type": "FM",
   "eqFilter": [
    {
     "type": "peak",
     "cutoffHz": 2378.41,
     "linearGain": 2.0
    },
    {
     "type": "low-pass",
     "cutoffHz": 5656.85,
     "linearGain": 1
    }
   ],
   "effects": [
    "reverb"
   ],
   "transition": "normal",
   "fadeInSeconds": 0.0263,
   "fadeOutTicks": -3,
   "chord": "simultaneous",
   "algorithm": "1←3 2←4",
   "feedbackType": "1⟲ 2⟲",
   "feedbackAmplitude": 4,
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 15
    },
    {
     "frequency": "1×",
     "amplitude": 12
    },
    {
     "frequency": "1×",
     "amplitude": 9
    },
    {
     "frequency": "~1×",
     "amplitude": 7
    }
   ],
   "envelopes": [
    {
     "target": "operatorAmplitude",
     "envelope": "swell 1",
     "index": 2
    },
    {
     "target": "operatorAmplitude",
     "envelope": "flare 2",
     "index": 3
    }
   ],
   "reverb": 33
  }
 },
 {
  "name": "French horn (F)",
  "preset": "french horn",
  "semitones": 7,
  "value": 708,
  "settings": {
   "type": "FM",
   "eqFilter": [
    {
     "type": "low-pass",
     "cutoffHz": 4000,
     "linearGain": 1
    },
    {
     "type": "peak",
     "cutoffHz": 2378.41,
     "linearGain": 2.8284
    }
   ],
   "effects": [
    "reverb"
   ],
   "reverb": 33,
   "fadeInSeconds": 0.0263,
   "fadeOutTicks": -3,
   "algorithm": "1←3 2←4",
   "feedbackType": "1⟲ 2⟲",
   "feedbackAmplitude": 3,
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 15
    },
    {
     "frequency": "1×",
     "amplitude": 12
    },
    {
     "frequency": "1×",
     "amplitude": 10
    },
    {
     "frequency": "~1×",
     "amplitude": 8
    }
   ],
   "envelopes": [
    {
     "target": "operatorAmplitude",
     "envelope": "swell 1",
     "index": 2
    },
    {
     "target": "operatorAmplitude",
     "envelope": "flare 2",
     "index": 3
    },
    {
     "target": "feedbackAmplitude",
     "envelope": "swell 1"
    }
   ]
  }
 },
 {
  "name": "Trombone",
  "preset": "trombone",
  "semitones": 0,
  "value": 705,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 2000,
   "filterResonance": 43,
   "filterEnvelope": "steady",
   "vibrato": "none",
   "algorithm": "1←(2 3 4)",
   "feedbackType": "2⟲",
   "feedbackAmplitude": 7,
   "feedbackEnvelope": "swell 1",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 14,
     "envelope": "custom"
    },
    {
     "frequency": "1×",
     "amplitude": 8,
     "envelope": "steady"
    },
    {
     "frequency": "1×",
     "amplitude": 0,
     "envelope": "steady"
    },
    {
     "frequency": "1×",
     "amplitude": 0,
     "envelope": "steady"
    }
   ]
  }
 },
 {
  "name": "Baritone horn",
  "preset": "baritone horn",
  "semitones": 0,
  "value": 1089,
  "settings": {
   "type": "FM",
   "eqFilter": [
    {
     "type": "low-pass",
     "cutoffHz": 3363.59,
     "linearGain": 1.4142
    }
   ],
   "effects": [
    "reverb"
   ],
   "transition": "normal",
   "fadeInSeconds": 0.0263,
   "fadeOutTicks": -3,
   "chord": "simultaneous",
   "algorithm": "1←(2 3 4)",
   "feedbackType": "2⟲",
   "feedbackAmplitude": 6,
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 15
    },
    {
     "frequency": "1×",
     "amplitude": 8
    },
    {
     "frequency": "1×",
     "amplitude": 3
    },
    {
     "frequency": "1×",
     "amplitude": 0
    }
   ],
   "envelopes": [
    {
     "target": "operatorAmplitude",
     "envelope": "swell 1",
     "index": 1
    }
   ],
   "reverb": 33
  }
 },
 {
  "name": "Euphonium",
  "preset": "baritone horn",
  "semitones": 0,
  "value": 1089,
  "settings": {
   "type": "FM",
   "eqFilter": [
    {
     "type": "low-pass",
     "cutoffHz": 3363.59,
     "linearGain": 1.4142
    }
   ],
   "effects": [
    "reverb"
   ],
   "transition": "normal",
   "fadeInSeconds": 0.0263,
   "fadeOutTicks": -3,
   "chord": "simultaneous",
   "algorithm": "1←(2 3 4)",
   "feedbackType": "2⟲",
   "feedbackAmplitude": 6,
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 15
    },
    {
     "frequency": "1×",
     "amplitude": 8
    },
    {
     "frequency": "1×",
     "amplitude": 3
    },
    {
     "frequency": "1×",
     "amplitude": 0
    }
   ],
   "envelopes": [
    {
     "target": "operatorAmplitude",
     "envelope": "swell 1",
     "index": 1
    }
   ],
   "reverb": 33
  }
 },
 {
  "name": "Tuba",
  "preset": "tuba",
  "semitones": 0,
  "value": 706,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 2000,
   "filterResonance": 43,
   "filterEnvelope": "steady",
   "vibrato": "none",
   "algorithm": "1←(2 3 4)",
   "feedbackType": "2⟲",
   "feedbackAmplitude": 8,
   "feedbackEnvelope": "swell 1",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 14,
     "envelope": "custom"
    },
    {
     "frequency": "1×",
     "amplitude": 6,
     "envelope": "steady"
    },
    {
     "frequency": "1×",
     "amplitude": 0,
     "envelope": "steady"
    },
    {
     "frequency": "1×",
     "amplitude": 0,
     "envelope": "steady"
    }
   ]
  }
 },
 {
  "name": "Sousaphone",
  "preset": "sousaphone",
  "semitones": 0,
  "value": 1090,
  "settings": {
   "type": "FM",
   "eqFilter": [
    {
     "type": "low-pass",
     "cutoffHz": 2000,
     "linearGain": 2.0
    },
    {
     "type": "high-pass",
     "cutoffHz": 62.5,
     "linearGain": 0.1768
    }
   ],
   "effects": [
    "reverb"
   ],
   "transition": "normal",
   "fadeInSeconds": 0.0263,
   "fadeOutTicks": -3,
   "chord": "simultaneous",
   "algorithm": "1←(2 3 4)",
   "feedbackType": "2⟲",
   "feedbackAmplitude": 8,
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 15
    },
    {
     "frequency": "1×",
     "amplitude": 6
    },
    {
     "frequency": "1×",
     "amplitude": 0
    },
    {
     "frequency": "1×",
     "amplitude": 0
    }
   ],
   "envelopes": [
    {
     "target": "operatorAmplitude",
     "envelope": "swell 1",
     "index": 1
    }
   ],
   "reverb": 33
  }
 },
 {
  "name": "Violin",
  "preset": "violin",
  "semitones": 0,
  "value": 576,
  "settings": {
   "type": "FM",
   "eqFilter": [
    {
     "type": "low-pass",
     "cutoffHz": 4000,
     "linearGain": 1.4142
    },
    {
     "type": "high-pass",
     "cutoffHz": 105.11,
     "linearGain": 0.3536
    }
   ],
   "effects": [
    "vibrato",
    "reverb"
   ],
   "vibrato": "delayed",
   "reverb": 67,
   "transition": "normal",
   "fadeInSeconds": 0.0413,
   "fadeOutTicks": 6,
   "chord": "simultaneous",
   "algorithm": "(1 2)←(3 4)",
   "feedbackType": "1→2",
   "feedbackAmplitude": 5,
   "operators": [
    {
     "frequency": "4×",
     "amplitude": 9
    },
    {
     "frequency": "3×",
     "amplitude": 9
    },
    {
     "frequency": "2×",
     "amplitude": 7
    },
    {
     "frequency": "7×",
     "amplitude": 5
    }
   ],
   "envelopes": [
    {
     "target": "operatorAmplitude",
     "envelope": "swell 1",
     "index": 3
    },
    {
     "target": "feedbackAmplitude",
     "envelope": "twang 3"
    }
   ]
  }
 },
 {
  "name": "Cello",
  "preset": "cello",
  "semitones": 0,
  "value": 578,
  "settings": {
   "type": "FM",
   "eqFilter": [
    {
     "type": "low-pass",
     "cutoffHz": 4000,
     "linearGain": 0.1768
    },
    {
     "type": "high-pass",
     "cutoffHz": 297.3,
     "linearGain": 0.7071
    },
    {
     "type": "peak",
     "cutoffHz": 4756.83,
     "linearGain": 5.6569
    }
   ],
   "effects": [
    "note filter",
    "reverb"
   ],
   "noteFilter": [
    {
     "type": "low-pass",
     "cutoffHz": 16000,
     "linearGain": 0.0884
    }
   ],
   "reverb": 67,
   "transition": "normal",
   "fadeInSeconds": 0.0125,
   "fadeOutTicks": 12,
   "chord": "simultaneous",
   "algorithm": "(1 2)←3←4",
   "feedbackType": "1⟲ 2⟲",
   "feedbackAmplitude": 3,
   "operators": [
    {
     "frequency": "16×",
     "amplitude": 5
    },
    {
     "frequency": "~1×",
     "amplitude": 10
    },
    {
     "frequency": "1×",
     "amplitude": 9
    },
    {
     "frequency": "6×",
     "amplitude": 3
    }
   ],
   "envelopes": [
    {
     "target": "noteFilterAllFreqs",
     "envelope": "swell 1"
    },
    {
     "target": "operatorAmplitude",
     "envelope": "swell 1",
     "index": 3
    }
   ]
  }
 },
 {
  "name": "Glockenspiel",
  "preset": "glockenspiel",
  "semitones": -24,
  "value": 193,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "hard fade",
   "chord": "strum",
   "filterCutoffHz": 5657,
   "filterResonance": 14,
   "filterEnvelope": "twang 2",
   "vibrato": "none",
   "algorithm": "(1 2 3)←4",
   "feedbackType": "1⟲ 2⟲ 3⟲",
   "feedbackAmplitude": 2,
   "feedbackEnvelope": "decay 1",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 7,
     "envelope": "custom"
    },
    {
     "frequency": "5×",
     "amplitude": 11,
     "envelope": "custom"
    },
    {
     "frequency": "8×",
     "amplitude": 7,
     "envelope": "custom"
    },
    {
     "frequency": "20×",
     "amplitude": 2,
     "envelope": "twang 1"
    }
   ]
  }
 },
 {
  "name": "Vibraphone",
  "preset": "vibraphone",
  "semitones": 0,
  "value": 196,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "hard fade",
   "chord": "harmony",
   "filterCutoffHz": 2828,
   "filterResonance": 14,
   "filterEnvelope": "twang 2",
   "vibrato": "none",
   "algorithm": "1 2 3 4",
   "feedbackType": "1→2→3→4",
   "feedbackAmplitude": 3,
   "feedbackEnvelope": "twang 1",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 9,
     "envelope": "custom"
    },
    {
     "frequency": "~1×",
     "amplitude": 9,
     "envelope": "custom"
    },
    {
     "frequency": "9×",
     "amplitude": 3,
     "envelope": "custom"
    },
    {
     "frequency": "4×",
     "amplitude": 9,
     "envelope": "custom"
    }
   ]
  }
 },
 {
  "name": "Marimba",
  "preset": "marimba",
  "semitones": 0,
  "value": 197,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "hard fade",
   "chord": "strum",
   "filterCutoffHz": 2000,
   "filterResonance": 29,
   "filterEnvelope": "decay 1",
   "vibrato": "none",
   "algorithm": "1 2←(3 4)",
   "feedbackType": "1⟲",
   "feedbackAmplitude": 0,
   "feedbackEnvelope": "steady",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 10,
     "envelope": "custom"
    },
    {
     "frequency": "4×",
     "amplitude": 6,
     "envelope": "custom"
    },
    {
     "frequency": "13×",
     "amplitude": 6,
     "envelope": "twang 1"
    },
    {
     "frequency": "1×",
     "amplitude": 0,
     "envelope": "steady"
    }
   ]
  }
 },
 {
  "name": "Xylophone",
  "preset": "xylophone",
  "semitones": -12,
  "value": 199,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "hard",
   "chord": "strum",
   "filterCutoffHz": 2000,
   "filterResonance": 14,
   "filterEnvelope": "twang 1",
   "vibrato": "none",
   "algorithm": "(1 2 3)←4",
   "feedbackType": "1⟲ 2⟲ 3⟲",
   "feedbackAmplitude": 0,
   "feedbackEnvelope": "steady",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 9,
     "envelope": "custom"
    },
    {
     "frequency": "6×",
     "amplitude": 9,
     "envelope": "custom"
    },
    {
     "frequency": "11×",
     "amplitude": 9,
     "envelope": "custom"
    },
    {
     "frequency": "20×",
     "amplitude": 6,
     "envelope": "twang 1"
    }
   ]
  }
 }
];
