// Generated by scripts/geninstruments.py - do not edit by hand.
// Each entry carries the preset that makes the sound and how far the part
// is written above concert pitch, so picking an instrument both re-voices
// the channel and transposes the notation.
var INSTRUMENTS = [
 {
  "name": "Piano",
  "preset": "grand piano",
  "semitones": 0,
  "value": 128,
  "settings": {
   "type": "Picked String",
   "eqFilter": [
    {
     "type": "high-pass",
     "cutoffHz": 148.65,
     "linearGain": 0.7071
    },
    {
     "type": "peak",
     "cutoffHz": 1681.79,
     "linearGain": 4
    },
    {
     "type": "low-pass",
     "cutoffHz": 8000,
     "linearGain": 0.1768
    },
    {
     "type": "peak",
     "cutoffHz": 3363.59,
     "linearGain": 4
    },
    {
     "type": "peak",
     "cutoffHz": 2378.41,
     "linearGain": 0.25
    }
   ],
   "effects": [
    "note filter",
    "reverb"
   ],
   "noteFilter": [
    {
     "type": "low-pass",
     "cutoffHz": 4756.83,
     "linearGain": 0.3536
    },
    {
     "type": "high-pass",
     "cutoffHz": 125,
     "linearGain": 0.0884
    }
   ],
   "reverb": 67,
   "fadeInSeconds": 0,
   "fadeOutTicks": 48,
   "harmonics": [
    100,
    100,
    86,
    86,
    86,
    71,
    71,
    71,
    0,
    71,
    71,
    71,
    71,
    57,
    57,
    71,
    57,
    14,
    57,
    57,
    57,
    57,
    57,
    57,
    57,
    57,
    29,
    57
   ],
   "unison": "piano",
   "stringSustain": 86,
   "stringSustainType": "acoustic",
   "envelopes": [
    {
     "target": "noteFilterFreq",
     "envelope": "note size",
     "index": 0
    },
    {
     "target": "noteFilterFreq",
     "envelope": "twang 1",
     "index": 1
    },
    {
     "target": "noteFilterFreq",
     "envelope": "twang 1",
     "index": 1
    }
   ]
  }
 },
 {
  "name": "Flute",
  "preset": "flute",
  "semitones": 0,
  "value": 832,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 5657,
   "filterResonance": 14,
   "filterEnvelope": "steady",
   "vibrato": "none",
   "algorithm": "1←(2 3 4)",
   "feedbackType": "4⟲",
   "feedbackAmplitude": 7,
   "feedbackEnvelope": "decay 2",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 15,
     "envelope": "custom"
    },
    {
     "frequency": "2×",
     "amplitude": 4,
     "envelope": "steady"
    },
    {
     "frequency": "1×",
     "amplitude": 3,
     "envelope": "steady"
    },
    {
     "frequency": "~1×",
     "amplitude": 1,
     "envelope": "punch"
    }
   ]
  }
 },
 {
  "name": "Piccolo",
  "preset": "piccolo",
  "semitones": -12,
  "value": 836,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 5657,
   "filterResonance": 43,
   "filterEnvelope": "steady",
   "vibrato": "none",
   "algorithm": "1←3 2←4",
   "feedbackType": "4⟲",
   "feedbackAmplitude": 15,
   "feedbackEnvelope": "twang 1",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 15,
     "envelope": "custom"
    },
    {
     "frequency": "1×",
     "amplitude": 10,
     "envelope": "custom"
    },
    {
     "frequency": "~2×",
     "amplitude": 3,
     "envelope": "punch"
    },
    {
     "frequency": "~1×",
     "amplitude": 5,
     "envelope": "punch"
    }
   ]
  }
 },
 {
  "name": "Oboe",
  "preset": "oboe",
  "semitones": 0,
  "value": 774,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "cross fade",
   "chord": "harmony",
   "filterCutoffHz": 4000,
   "filterResonance": 14,
   "filterEnvelope": "swell 1",
   "vibrato": "none",
   "algorithm": "1 2←(3 4)",
   "feedbackType": "2⟲",
   "feedbackAmplitude": 2,
   "feedbackEnvelope": "tremolo5",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 7,
     "envelope": "custom"
    },
    {
     "frequency": "4×",
     "amplitude": 12,
     "envelope": "custom"
    },
    {
     "frequency": "1×",
     "amplitude": 6,
     "envelope": "steady"
    },
    {
     "frequency": "6×",
     "amplitude": 2,
     "envelope": "steady"
    }
   ]
  }
 },
 {
  "name": "Bassoon",
  "preset": "bassoon",
  "semitones": 0,
  "value": 776,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 707,
   "filterResonance": 57,
   "filterEnvelope": "steady",
   "vibrato": "none",
   "algorithm": "1←(2 3←4)",
   "feedbackType": "1⟲",
   "feedbackAmplitude": 2,
   "feedbackEnvelope": "steady",
   "operators": [
    {
     "frequency": "2×",
     "amplitude": 11,
     "envelope": "custom"
    },
    {
     "frequency": "1×",
     "amplitude": 6,
     "envelope": "steady"
    },
    {
     "frequency": "6×",
     "amplitude": 6,
     "envelope": "swell 1"
    },
    {
     "frequency": "1×",
     "amplitude": 0,
     "envelope": "steady"
    }
   ]
  }
 },
 {
  "name": "Clarinet (B♭)",
  "preset": "clarinet",
  "semitones": 2,
  "value": 777,
  "settings": {
   "type": "harmonics",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 1414,
   "filterResonance": 14,
   "filterEnvelope": "steady",
   "interval": "union",
   "vibrato": "none",
   "harmonics": [
    100,
    43,
    86,
    57,
    86,
    71,
    86,
    71,
    71,
    71,
    71,
    71,
    71,
    43,
    71,
    71,
    57,
    57,
    57,
    57,
    57,
    57,
    43,
    43,
    43,
    29,
    14,
    0
   ]
  }
 },
 {
  "name": "Soprano sax (B♭)",
  "preset": "soprano sax",
  "semitones": 2,
  "value": 768,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 2000,
   "filterResonance": 29,
   "filterEnvelope": "steady",
   "vibrato": "none",
   "algorithm": "1←2←3←4",
   "feedbackType": "4⟲",
   "feedbackAmplitude": 5,
   "feedbackEnvelope": "swell 1",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 13,
     "envelope": "custom"
    },
    {
     "frequency": "4×",
     "amplitude": 4,
     "envelope": "swell 1"
    },
    {
     "frequency": "1×",
     "amplitude": 7,
     "envelope": "steady"
    },
    {
     "frequency": "5×",
     "amplitude": 4,
     "envelope": "punch"
    }
   ]
  }
 },
 {
  "name": "Alto sax (E♭)",
  "preset": "alto sax",
  "semitones": 9,
  "value": 769,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 2000,
   "filterResonance": 43,
   "filterEnvelope": "steady",
   "vibrato": "none",
   "algorithm": "1←(2 3←4)",
   "feedbackType": "1⟲",
   "feedbackAmplitude": 4,
   "feedbackEnvelope": "punch",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 13,
     "envelope": "custom"
    },
    {
     "frequency": "1×",
     "amplitude": 6,
     "envelope": "steady"
    },
    {
     "frequency": "4×",
     "amplitude": 6,
     "envelope": "swell 1"
    },
    {
     "frequency": "1×",
     "amplitude": 12,
     "envelope": "steady"
    }
   ]
  }
 },
 {
  "name": "Tenor sax (B♭)",
  "preset": "tenor sax",
  "semitones": 14,
  "value": 770,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 2828,
   "filterResonance": 29,
   "filterEnvelope": "steady",
   "vibrato": "none",
   "algorithm": "1←2←3←4",
   "feedbackType": "1⟲",
   "feedbackAmplitude": 6,
   "feedbackEnvelope": "swell 1",
   "operators": [
    {
     "frequency": "2×",
     "amplitude": 12,
     "envelope": "custom"
    },
    {
     "frequency": "3×",
     "amplitude": 7,
     "envelope": "steady"
    },
    {
     "frequency": "1×",
     "amplitude": 3,
     "envelope": "steady"
    },
    {
     "frequency": "8×",
     "amplitude": 3,
     "envelope": "steady"
    }
   ]
  }
 },
 {
  "name": "Baritone sax (E♭)",
  "preset": "baritone sax",
  "semitones": 21,
  "value": 771,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 2828,
   "filterResonance": 0,
   "filterEnvelope": "steady",
   "vibrato": "none",
   "algorithm": "1←(2 3←4)",
   "feedbackType": "1⟲",
   "feedbackAmplitude": 2,
   "feedbackEnvelope": "swell 2",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 12,
     "envelope": "custom"
    },
    {
     "frequency": "8×",
     "amplitude": 4,
     "envelope": "steady"
    },
    {
     "frequency": "4×",
     "amplitude": 5,
     "envelope": "steady"
    },
    {
     "frequency": "1×",
     "amplitude": 4,
     "envelope": "punch"
    }
   ]
  }
 },
 {
  "name": "Trumpet (B♭)",
  "preset": "trumpet",
  "semitones": 2,
  "value": 704,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 2828,
   "filterResonance": 43,
   "filterEnvelope": "steady",
   "vibrato": "none",
   "algorithm": "1←(2 3 4)",
   "feedbackType": "1⟲",
   "feedbackAmplitude": 9,
   "feedbackEnvelope": "swell 1",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 14,
     "envelope": "custom"
    },
    {
     "frequency": "1×",
     "amplitude": 8,
     "envelope": "steady"
    },
    {
     "frequency": "1×",
     "amplitude": 5,
     "envelope": "flare 2"
    },
    {
     "frequency": "1×",
     "amplitude": 0,
     "envelope": "steady"
    }
   ]
  }
 },
 {
  "name": "Mellophone (F)",
  "preset": "mellophone",
  "semitones": 7,
  "value": 1088,
  "settings": {
   "type": "FM",
   "eqFilter": [
    {
     "type": "peak",
     "cutoffHz": 2378.41,
     "linearGain": 2.0
    },
    {
     "type": "low-pass",
     "cutoffHz": 5656.85,
     "linearGain": 1
    }
   ],
   "effects": [
    "reverb"
   ],
   "transition": "normal",
   "fadeInSeconds": 0.0263,
   "fadeOutTicks": -3,
   "chord": "simultaneous",
   "algorithm": "1←3 2←4",
   "feedbackType": "1⟲ 2⟲",
   "feedbackAmplitude": 4,
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 15
    },
    {
     "frequency": "1×",
     "amplitude": 12
    },
    {
     "frequency": "1×",
     "amplitude": 9
    },
    {
     "frequency": "~1×",
     "amplitude": 7
    }
   ],
   "envelopes": [
    {
     "target": "operatorAmplitude",
     "envelope": "swell 1",
     "index": 2
    },
    {
     "target": "operatorAmplitude",
     "envelope": "flare 2",
     "index": 3
    }
   ],
   "reverb": 33
  }
 },
 {
  "name": "French horn (F)",
  "preset": "french horn",
  "semitones": 7,
  "value": 708,
  "settings": {
   "type": "FM",
   "eqFilter": [
    {
     "type": "low-pass",
     "cutoffHz": 4000,
     "linearGain": 1
    },
    {
     "type": "peak",
     "cutoffHz": 2378.41,
     "linearGain": 2.8284
    }
   ],
   "effects": [
    "reverb"
   ],
   "reverb": 33,
   "fadeInSeconds": 0.0263,
   "fadeOutTicks": -3,
   "algorithm": "1←3 2←4",
   "feedbackType": "1⟲ 2⟲",
   "feedbackAmplitude": 3,
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 15
    },
    {
     "frequency": "1×",
     "amplitude": 12
    },
    {
     "frequency": "1×",
     "amplitude": 10
    },
    {
     "frequency": "~1×",
     "amplitude": 8
    }
   ],
   "envelopes": [
    {
     "target": "operatorAmplitude",
     "envelope": "swell 1",
     "index": 2
    },
    {
     "target": "operatorAmplitude",
     "envelope": "flare 2",
     "index": 3
    },
    {
     "target": "feedbackAmplitude",
     "envelope": "swell 1"
    }
   ]
  }
 },
 {
  "name": "Trombone",
  "preset": "trombone",
  "semitones": 0,
  "value": 705,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 2000,
   "filterResonance": 43,
   "filterEnvelope": "steady",
   "vibrato": "none",
   "algorithm": "1←(2 3 4)",
   "feedbackType": "2⟲",
   "feedbackAmplitude": 7,
   "feedbackEnvelope": "swell 1",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 14,
     "envelope": "custom"
    },
    {
     "frequency": "1×",
     "amplitude": 8,
     "envelope": "steady"
    },
    {
     "frequency": "1×",
     "amplitude": 0,
     "envelope": "steady"
    },
    {
     "frequency": "1×",
     "amplitude": 0,
     "envelope": "steady"
    }
   ]
  }
 },
 {
  "name": "Baritone horn",
  "preset": "baritone horn",
  "semitones": 0,
  "value": 1089,
  "settings": {
   "type": "FM",
   "eqFilter": [
    {
     "type": "low-pass",
     "cutoffHz": 3363.59,
     "linearGain": 1.4142
    }
   ],
   "effects": [
    "reverb"
   ],
   "transition": "normal",
   "fadeInSeconds": 0.0263,
   "fadeOutTicks": -3,
   "chord": "simultaneous",
   "algorithm": "1←(2 3 4)",
   "feedbackType": "2⟲",
   "feedbackAmplitude": 6,
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 15
    },
    {
     "frequency": "1×",
     "amplitude": 8
    },
    {
     "frequency": "1×",
     "amplitude": 3
    },
    {
     "frequency": "1×",
     "amplitude": 0
    }
   ],
   "envelopes": [
    {
     "target": "operatorAmplitude",
     "envelope": "swell 1",
     "index": 1
    }
   ],
   "reverb": 33
  }
 },
 {
  "name": "Euphonium",
  "preset": "baritone horn",
  "semitones": 0,
  "value": 1089,
  "settings": {
   "type": "FM",
   "eqFilter": [
    {
     "type": "low-pass",
     "cutoffHz": 3363.59,
     "linearGain": 1.4142
    }
   ],
   "effects": [
    "reverb"
   ],
   "transition": "normal",
   "fadeInSeconds": 0.0263,
   "fadeOutTicks": -3,
   "chord": "simultaneous",
   "algorithm": "1←(2 3 4)",
   "feedbackType": "2⟲",
   "feedbackAmplitude": 6,
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 15
    },
    {
     "frequency": "1×",
     "amplitude": 8
    },
    {
     "frequency": "1×",
     "amplitude": 3
    },
    {
     "frequency": "1×",
     "amplitude": 0
    }
   ],
   "envelopes": [
    {
     "target": "operatorAmplitude",
     "envelope": "swell 1",
     "index": 1
    }
   ],
   "reverb": 33
  }
 },
 {
  "name": "Tuba",
  "preset": "tuba",
  "semitones": 0,
  "value": 706,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "soft",
   "chord": "harmony",
   "filterCutoffHz": 2000,
   "filterResonance": 43,
   "filterEnvelope": "steady",
   "vibrato": "none",
   "algorithm": "1←(2 3 4)",
   "feedbackType": "2⟲",
   "feedbackAmplitude": 8,
   "feedbackEnvelope": "swell 1",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 14,
     "envelope": "custom"
    },
    {
     "frequency": "1×",
     "amplitude": 6,
     "envelope": "steady"
    },
    {
     "frequency": "1×",
     "amplitude": 0,
     "envelope": "steady"
    },
    {
     "frequency": "1×",
     "amplitude": 0,
     "envelope": "steady"
    }
   ]
  }
 },
 {
  "name": "Sousaphone",
  "preset": "sousaphone",
  "semitones": 0,
  "value": 1090,
  "settings": {
   "type": "FM",
   "eqFilter": [
    {
     "type": "low-pass",
     "cutoffHz": 2000,
     "linearGain": 2.0
    },
    {
     "type": "high-pass",
     "cutoffHz": 62.5,
     "linearGain": 0.1768
    }
   ],
   "effects": [
    "reverb"
   ],
   "transition": "normal",
   "fadeInSeconds": 0.0263,
   "fadeOutTicks": -3,
   "chord": "simultaneous",
   "algorithm": "1←(2 3 4)",
   "feedbackType": "2⟲",
   "feedbackAmplitude": 8,
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 15
    },
    {
     "frequency": "1×",
     "amplitude": 6
    },
    {
     "frequency": "1×",
     "amplitude": 0
    },
    {
     "frequency": "1×",
     "amplitude": 0
    }
   ],
   "envelopes": [
    {
     "target": "operatorAmplitude",
     "envelope": "swell 1",
     "index": 1
    }
   ],
   "reverb": 33
  }
 },
 {
  "name": "Violin",
  "preset": "violin",
  "semitones": 0,
  "value": 576,
  "settings": {
   "type": "FM",
   "eqFilter": [
    {
     "type": "low-pass",
     "cutoffHz": 4000,
     "linearGain": 1.4142
    },
    {
     "type": "high-pass",
     "cutoffHz": 105.11,
     "linearGain": 0.3536
    }
   ],
   "effects": [
    "vibrato",
    "reverb"
   ],
   "vibrato": "delayed",
   "reverb": 67,
   "transition": "normal",
   "fadeInSeconds": 0.0413,
   "fadeOutTicks": 6,
   "chord": "simultaneous",
   "algorithm": "(1 2)←(3 4)",
   "feedbackType": "1→2",
   "feedbackAmplitude": 5,
   "operators": [
    {
     "frequency": "4×",
     "amplitude": 9
    },
    {
     "frequency": "3×",
     "amplitude": 9
    },
    {
     "frequency": "2×",
     "amplitude": 7
    },
    {
     "frequency": "7×",
     "amplitude": 5
    }
   ],
   "envelopes": [
    {
     "target": "operatorAmplitude",
     "envelope": "swell 1",
     "index": 3
    },
    {
     "target": "feedbackAmplitude",
     "envelope": "twang 3"
    }
   ]
  }
 },
 {
  "name": "Cello",
  "preset": "cello",
  "semitones": 0,
  "value": 578,
  "settings": {
   "type": "FM",
   "eqFilter": [
    {
     "type": "low-pass",
     "cutoffHz": 4000,
     "linearGain": 0.1768
    },
    {
     "type": "high-pass",
     "cutoffHz": 297.3,
     "linearGain": 0.7071
    },
    {
     "type": "peak",
     "cutoffHz": 4756.83,
     "linearGain": 5.6569
    }
   ],
   "effects": [
    "note filter",
    "reverb"
   ],
   "noteFilter": [
    {
     "type": "low-pass",
     "cutoffHz": 16000,
     "linearGain": 0.0884
    }
   ],
   "reverb": 67,
   "transition": "normal",
   "fadeInSeconds": 0.0125,
   "fadeOutTicks": 12,
   "chord": "simultaneous",
   "algorithm": "(1 2)←3←4",
   "feedbackType": "1⟲ 2⟲",
   "feedbackAmplitude": 3,
   "operators": [
    {
     "frequency": "16×",
     "amplitude": 5
    },
    {
     "frequency": "~1×",
     "amplitude": 10
    },
    {
     "frequency": "1×",
     "amplitude": 9
    },
    {
     "frequency": "6×",
     "amplitude": 3
    }
   ],
   "envelopes": [
    {
     "target": "noteFilterAllFreqs",
     "envelope": "swell 1"
    },
    {
     "target": "operatorAmplitude",
     "envelope": "swell 1",
     "index": 3
    }
   ]
  }
 },
 {
  "name": "Glockenspiel",
  "preset": "glockenspiel",
  "semitones": -24,
  "value": 193,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "hard fade",
   "chord": "strum",
   "filterCutoffHz": 5657,
   "filterResonance": 14,
   "filterEnvelope": "twang 2",
   "vibrato": "none",
   "algorithm": "(1 2 3)←4",
   "feedbackType": "1⟲ 2⟲ 3⟲",
   "feedbackAmplitude": 2,
   "feedbackEnvelope": "decay 1",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 7,
     "envelope": "custom"
    },
    {
     "frequency": "5×",
     "amplitude": 11,
     "envelope": "custom"
    },
    {
     "frequency": "8×",
     "amplitude": 7,
     "envelope": "custom"
    },
    {
     "frequency": "20×",
     "amplitude": 2,
     "envelope": "twang 1"
    }
   ]
  }
 },
 {
  "name": "Vibraphone",
  "preset": "vibraphone",
  "semitones": 0,
  "value": 196,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "hard fade",
   "chord": "harmony",
   "filterCutoffHz": 2828,
   "filterResonance": 14,
   "filterEnvelope": "twang 2",
   "vibrato": "none",
   "algorithm": "1 2 3 4",
   "feedbackType": "1→2→3→4",
   "feedbackAmplitude": 3,
   "feedbackEnvelope": "twang 1",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 9,
     "envelope": "custom"
    },
    {
     "frequency": "~1×",
     "amplitude": 9,
     "envelope": "custom"
    },
    {
     "frequency": "9×",
     "amplitude": 3,
     "envelope": "custom"
    },
    {
     "frequency": "4×",
     "amplitude": 9,
     "envelope": "custom"
    }
   ]
  }
 },
 {
  "name": "Marimba",
  "preset": "marimba",
  "semitones": 0,
  "value": 197,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "hard fade",
   "chord": "strum",
   "filterCutoffHz": 2000,
   "filterResonance": 29,
   "filterEnvelope": "decay 1",
   "vibrato": "none",
   "algorithm": "1 2←(3 4)",
   "feedbackType": "1⟲",
   "feedbackAmplitude": 0,
   "feedbackEnvelope": "steady",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 10,
     "envelope": "custom"
    },
    {
     "frequency": "4×",
     "amplitude": 6,
     "envelope": "custom"
    },
    {
     "frequency": "13×",
     "amplitude": 6,
     "envelope": "twang 1"
    },
    {
     "frequency": "1×",
     "amplitude": 0,
     "envelope": "steady"
    }
   ]
  }
 },
 {
  "name": "Xylophone",
  "preset": "xylophone",
  "semitones": -12,
  "value": 199,
  "settings": {
   "type": "FM",
   "effects": "reverb",
   "transition": "hard",
   "chord": "strum",
   "filterCutoffHz": 2000,
   "filterResonance": 14,
   "filterEnvelope": "twang 1",
   "vibrato": "none",
   "algorithm": "(1 2 3)←4",
   "feedbackType": "1⟲ 2⟲ 3⟲",
   "feedbackAmplitude": 0,
   "feedbackEnvelope": "steady",
   "operators": [
    {
     "frequency": "1×",
     "amplitude": 9,
     "envelope": "custom"
    },
    {
     "frequency": "6×",
     "amplitude": 9,
     "envelope": "custom"
    },
    {
     "frequency": "11×",
     "amplitude": 9,
     "envelope": "custom"
    },
    {
     "frequency": "20×",
     "amplitude": 6,
     "envelope": "twang 1"
    }
   ]
  }
 }
];
// Sheet music rendering for BeepBox: Reborn.
//
// Takes the notes a user entered and draws them as notation, optionally
// transposed for a transposing instrument. BeepBox songs are in concert pitch,
// so "written pitch = sounding pitch + the part's interval".
var SheetMusic = (function () {
	"use strict";

	var SVGNS = "http://www.w3.org/2000/svg";

	// How far above concert pitch each instrument reads.
	var parts = [
		{name: "Concert pitch (no change)",   semitones: 0},
		{name: "B♭  trumpet, clarinet",  semitones: 2},
		{name: "E♭  alto sax, bari sax", semitones: 9},
		{name: "F  horn",                     semitones: 7},
		{name: "B♭ bass  tenor sax",     semitones: 14},
	];

	var COLORS = ["#25F3FF", "#FFFF25", "#FF9752", "#86FF25", "#FF90FF", "#9F31FF",
	              "#25C2FF", "#DFFF25", "#FF6A25", "#25FFC9"];
	function channelColor(i) { return COLORS[i % COLORS.length]; }

	// letter index (C=0..B=6) and accidental (-1 flat, 0 natural, 1 sharp)
	var SHARP_SPELL = [[0,0],[0,1],[1,0],[1,1],[2,0],[3,0],[3,1],[4,0],[4,1],[5,0],[5,1],[6,0]];
	var FLAT_SPELL  = [[0,0],[1,-1],[1,0],[2,-1],[2,0],[3,0],[4,-1],[4,0],[5,-1],[5,0],[6,-1],[6,0]];
	var LETTER_SEMITONE = [0, 2, 4, 5, 7, 9, 11];

	// written key pitch class -> key signature
	var KEY_SIG = {
		0:  {type: 0, count: 0}, 7:  {type: 1, count: 1}, 2:  {type: 1, count: 2},
		9:  {type: 1, count: 3}, 4:  {type: 1, count: 4}, 11: {type: 1, count: 5},
		6:  {type: 1, count: 6}, 5:  {type: -1, count: 1}, 10: {type: -1, count: 2},
		3:  {type: -1, count: 3}, 8:  {type: -1, count: 4}, 1:  {type: -1, count: 5},
	};
	var SHARP_ORDER = [3, 0, 4, 1, 5, 2, 6];   // F C G D A E B
	var FLAT_ORDER  = [6, 2, 5, 1, 4, 0, 3];   // B E A D G C F

	// Where each key-signature accidental sits, in half-steps above the bottom
	// staff line. Fixed by convention, not derived from the pitch.
	var SIG_POS = {
		treble: {sharp: [8, 5, 9, 6, 3, 7, 4], flat: [4, 7, 3, 6, 2, 5, 1]},
		bass:   {sharp: [6, 3, 7, 4, 1, 5, 2], flat: [2, 5, 1, 4, 0, 3, -1]},
	};

	function spell(midi, useSharps) {
		var pc = ((midi % 12) + 12) % 12;
		var entry = (useSharps ? SHARP_SPELL : FLAT_SPELL)[pc];
		var letter = entry[0], accidental = entry[1];
		// octave of the *letter*, so Cb/B# land on the right line
		var octave = Math.floor((midi - accidental) / 12) - 1;
		return {letter: letter, accidental: accidental, octave: octave,
		        diatonic: octave * 7 + letter};
	}

	function el(name, attrs, parent) {
		var e = document.createElementNS(SVGNS, name);
		for (var k in attrs) if (attrs.hasOwnProperty(k)) e.setAttribute(k, String(attrs[k]));
		if (parent) parent.appendChild(e);
		return e;
	}

	function glyph(parent, x, y, text, size, color) {
		var t = el("text", {x: x, y: y, "font-size": size || 16,
			"font-family": "Georgia, 'Times New Roman', serif", fill: color || "#000"}, parent);
		t.textContent = text;
		return t;
	}

	// ---- collecting the notes the user actually entered ---------------------
	function collectNotes(song, channelIndex) {
		var channel = song.channels[channelIndex];
		var partsPerBar = song.beatsPerBar * beepbox.Config.partsPerBeat;
		var out = [];
		for (var bar = 0; bar < song.barCount; bar++) {
			var patternIndex = channel.bars[bar];
			if (!patternIndex) continue;
			var pattern = channel.patterns[patternIndex - 1];
			if (!pattern) continue;
			for (var n = 0; n < pattern.notes.length; n++) {
				var note = pattern.notes[n];
				for (var p = 0; p < note.pitches.length; p++) {
					out.push({
						bar: bar,
						start: bar * partsPerBar + note.start,
						duration: note.end - note.start,
						pitch: note.pitches[p],
					});
				}
			}
		}
		out.sort(function (a, b) { return a.start - b.start || a.pitch - b.pitch; });
		return out;
	}

	function durationGlyph(parts_, partsPerBeat) {
		var beats = parts_ / partsPerBeat;
		if (beats >= 4)   return {filled: false, stem: false, flags: 0, dotted: false};
		if (beats >= 3)   return {filled: false, stem: true,  flags: 0, dotted: true};
		if (beats >= 2)   return {filled: false, stem: true,  flags: 0, dotted: false};
		if (beats >= 1.5) return {filled: true,  stem: true,  flags: 0, dotted: true};
		if (beats >= 1)   return {filled: true,  stem: true,  flags: 0, dotted: false};
		if (beats >= 0.5) return {filled: true,  stem: true,  flags: 1, dotted: false};
		return {filled: true, stem: true, flags: 2, dotted: false};
	}

	// ---- the renderer --------------------------------------------------------
	// instrument: {name, semitones} or null to leave the part at concert pitch.
	function renderChannel(song, channelIndex, instrument) {
		var notes = collectNotes(song, channelIndex);
		var part = instrument || {name: "Concert pitch", semitones: 0};
		var basePitch = beepbox.Config.keys[song.key].basePitch;
		var partsPerBeat = beepbox.Config.partsPerBeat;
		var partsPerBar = song.beatsPerBar * partsPerBeat;

		var container = document.createElement("div");
		var title = document.createElement("div");
		title.className = "part-title";
		var KEY_NAMES = ["C", "D\u266D", "D", "E\u266D", "E", "F",
		                 "G\u266D", "G", "A\u266D", "A", "B\u266D", "B"];
		var writtenKeyName = KEY_NAMES[((song.key + part.semitones) % 12 + 12) % 12];
		title.innerHTML = "Channel " + (channelIndex + 1) +
			' <span>&mdash; ' + part.name +
			(part.semitones ? " &middot; written in " + writtenKeyName +
				" (sounds " + KEY_NAMES[song.key] + ")" : " &middot; " + KEY_NAMES[song.key]) +
			"</span>";
		container.appendChild(title);

		if (notes.length === 0) {
			var empty = document.createElement("div");
			empty.className = "empty";
			empty.textContent = "No notes in this channel.";
			container.appendChild(empty);
			return container;
		}

		// written pitch = sounding + the part's interval
		for (var i = 0; i < notes.length; i++) {
			notes[i].midi = basePitch + notes[i].pitch + part.semitones;
		}

		var writtenKey = ((song.key + part.semitones) % 12 + 12) % 12;
		var sig = KEY_SIG[writtenKey] || {type: 0, count: 0};
		var useSharps = sig.type >= 0;

		// clef from the middle of the range
		var sorted = notes.map(function (n) { return n.midi; }).sort(function (a, b) { return a - b; });
		var median = sorted[Math.floor(sorted.length / 2)];
		var treble = median >= 57;
		// diatonic index of the bottom staff line: E4 for treble, G2 for bass
		var bottomDiatonic = treble ? spell(64, useSharps).diatonic : spell(43, useSharps).diatonic;

		// geometry
		var GAP = 7;                          // half a staff space
		var STAFF = GAP * 8;                  // four spaces
		var LEFT = 34 + Math.max(1, sig.count) * 8 + 26;   // clef + key signature + time signature
		var BAR_W = Math.max(90, 34 * song.beatsPerBar);
		var PER_LINE = Math.max(1, Math.min(4, Math.floor(760 / BAR_W)));
		var lines = Math.ceil(song.barCount / PER_LINE);
		var LINE_H = STAFF + 58;
		var width = LEFT + PER_LINE * BAR_W + 16;
		var height = lines * LINE_H + 16;

		var svg = el("svg", {width: width, height: height,
			viewBox: "0 0 " + width + " " + height, xmlns: SVGNS});

		// tempo mark, written above the first system
		glyph(svg, 8, 16, "\u2669 = " + song.tempo, 12);

		var clefs = [];

		for (var line = 0; line < lines; line++) {
			var top = 30 + line * LINE_H;
			var x0 = LEFT;
			var barsHere = Math.min(PER_LINE, song.barCount - line * PER_LINE);
			var lineW = barsHere * BAR_W;

			for (var s = 0; s < 5; s++) {
				el("line", {x1: 8, y1: top + s * GAP * 2, x2: x0 + lineW, y2: top + s * GAP * 2,
					stroke: "#000", "stroke-width": 1}, svg);
			}
			// Clef. A treble clef must curl around the G line (2nd from the
			// bottom) and a bass clef sit on the F line (2nd from the top) -
			// that is the reference a reader counts from, so a clef placed by
			// guesswork shifts every note. Font metrics for these glyphs vary,
			// so measure the drawn glyph and align its centre to that line
			// rather than trusting an offset.
			clefs.push({
				node: glyph(svg, 12, top + STAFF / 2, treble ? "\u{1D11E}" : "\u{1D122}",
					treble ? 46 : 38),
				lineY: top + STAFF - (treble ? 2 : 6) * GAP,
				// Where the reference point sits within the glyph: the treble
				// spiral is low in its box, the bass curl and dots are high.
				anchor: treble ? 0.72 : 0.26,
			});

			// key signature, at the conventional staff positions
			var posList = SIG_POS[treble ? "treble" : "bass"][sig.type >= 0 ? "sharp" : "flat"];
			for (var k = 0; k < sig.count; k++) {
				var ky = top + STAFF - posList[k] * GAP;
				glyph(svg, 30 + k * 8, ky + 5, sig.type >= 0 ? "♯" : "♭", 15);
			}

			// time signature, once, at the start
			if (line === 0) {
				var tsx = LEFT - 11;
				var unit = song.beatUnit || 4;
				glyph(svg, tsx, top + GAP * 3.6, String(song.beatsPerBar), 15);
				glyph(svg, tsx, top + STAFF - 1, String(unit), 15);
			}

			// barlines
			for (var b = 0; b <= barsHere; b++) {
				el("line", {x1: x0 + b * BAR_W, y1: top, x2: x0 + b * BAR_W, y2: top + STAFF,
					stroke: "#000", "stroke-width": b === barsHere ? 2 : 1}, svg);
			}

			// notes on this line
			for (var ni = 0; ni < notes.length; ni++) {
				var note = notes[ni];
				var barOnLine = note.bar - line * PER_LINE;
				if (barOnLine < 0 || barOnLine >= barsHere) continue;

				var within = (note.start % partsPerBar) / partsPerBar;
				var cx = x0 + barOnLine * BAR_W + 14 + within * (BAR_W - 22);
				var sp = spell(note.midi, useSharps);
				var steps = sp.diatonic - bottomDiatonic;
				var cy = top + STAFF - steps * GAP;
				var shape = durationGlyph(note.duration, partsPerBeat);

				// ledger lines
				var L;
				for (L = -2; steps <= L; L -= 2) {
					el("line", {x1: cx - 9, y1: top + STAFF - L * GAP, x2: cx + 9,
						y2: top + STAFF - L * GAP, stroke: "#000", "stroke-width": 1}, svg);
				}
				for (L = 10; steps >= L; L += 2) {
					el("line", {x1: cx - 9, y1: top + STAFF - L * GAP, x2: cx + 9,
						y2: top + STAFF - L * GAP, stroke: "#000", "stroke-width": 1}, svg);
				}

				el("ellipse", {cx: cx, cy: cy, rx: 5.4, ry: 4,
					fill: shape.filled ? "#000" : "none",
					stroke: "#000", "stroke-width": shape.filled ? 0 : 1.4,
					transform: "rotate(-20 " + cx + " " + cy + ")"}, svg);

				if (shape.dotted) el("circle", {cx: cx + 10, cy: cy - 3, r: 1.5, fill: "#000"}, svg);

				if (shape.stem) {
					var up = steps < 4;
					var sx = cx + (up ? 5 : -5);
					var sy2 = cy + (up ? -26 : 26);
					el("line", {x1: sx, y1: cy, x2: sx, y2: sy2, stroke: "#000", "stroke-width": 1.3}, svg);
					for (var fl = 0; fl < shape.flags; fl++) {
						el("path", {d: "M " + sx + " " + (sy2 + fl * 6 * (up ? 1 : -1)) +
							" q 9 4 7 13", stroke: "#000", "stroke-width": 1.3, fill: "none"}, svg);
					}
				}

				// accidental when the note is not covered by the key signature
				var inKey = isInKeySignature(sp, sig);
				if (!inKey) {
					glyph(svg, cx - 17, cy + 5,
						sp.accidental === 1 ? "♯" : sp.accidental === -1 ? "♭" : "♮", 14);
				}
			}

			// measure numbers
			for (var m = 0; m < barsHere; m++) {
				glyph(svg, x0 + m * BAR_W + 2, top - 6, String(line * PER_LINE + m + 1), 9, "#888");
			}
		}

		container.appendChild(svg);

		// getBBox only reports real numbers once the node is actually in the
		// document, and this container is still detached, so align on the next
		// frame - by then the caller has appended it.
		alignClefsLater(clefs);
		return container;
	}

	function alignClefsLater(clefs) {
		if (!clefs.length) return;
		var run = function () {
			for (var c = 0; c < clefs.length; c++) {
				var node = clefs[c].node, box;
				try { box = node.getBBox(); } catch (e) { continue; }
				if (!box || !box.height) continue;
				var anchorY = box.y + box.height * clefs[c].anchor;
				node.setAttribute("y", String(
					parseFloat(node.getAttribute("y")) + (clefs[c].lineY - anchorY)));
			}
		};
		if (typeof requestAnimationFrame === "function") requestAnimationFrame(run);
		else setTimeout(run, 0);
	}

	function isInKeySignature(sp, sig) {
		var order = sig.type >= 0 ? SHARP_ORDER : FLAT_ORDER;
		var affected = order.slice(0, sig.count);
		var isAffected = affected.indexOf(sp.letter) !== -1;
		if (isAffected) return sp.accidental === (sig.type >= 0 ? 1 : -1);
		return sp.accidental === 0;
	}

	return {
		parts: parts,
		channelColor: channelColor,
		renderChannel: renderChannel,
	};
}());
/* The transpose + sheet music interface, in one place so it can run either as
   its own page (transpose.html, when the site is served) or as an overlay
   inside the editor itself (beepbox_offline.html, which is a single file and
   has no transpose.html next to it to navigate to).

   Needs beepbox (Song/Config), INSTRUMENTS and SheetMusic to already be loaded. */
var TransposeUI = (function () {
	"use strict";

	// Every selector is scoped under .tui. The overlay drops this markup into the
	// editor page, which has button/select rules of its own that would otherwise
	// fight with these.
	var CSS = [
		".tui { font-family: 'Roboto', sans-serif; font-size: 13px; line-height: 1.4; color: #fff; text-align: left; }",
		".tui h1 { font-size: 20px; margin: 0 0 2px 0; }",
		".tui .sub { color: #999; margin-bottom: 18px; }",
		".tui a { color: #ff4452; }",
		".tui .row { display: flex; align-items: center; gap: 10px; padding: 8px 10px; margin-bottom: 6px; background: #1c1c1c; border-radius: 5px; }",
		".tui .swatch { width: 10px; height: 22px; border-radius: 3px; flex-shrink: 0; }",
		".tui .name { flex: 1; min-width: 0; }",
		".tui .name b { display: block; }",
		".tui .name span { color: #999; font-size: 12px; }",
		".tui select { background: #444; color: #fff; border: none; border-radius: 4px; height: 26px; font-family: inherit; font-size: 12px; padding: 0 6px; max-width: 230px; }",
		".tui button { background: #444; color: #fff; border: none; border-radius: 5px; height: 30px; padding: 0 14px; font-family: inherit; font-size: 13px; cursor: pointer; }",
		".tui button:hover { background: #555; }",
		".tui button.primary { background: #ff4452; color: #fff; font-weight: bold; }",
		".tui button.primary:hover { filter: brightness(1.1); }",
		".tui .bar { display: flex; gap: 8px; align-items: center; margin: 16px 0; flex-wrap: wrap; }",
		".tui .note { color: #999; font-size: 12px; }",
		".tui .sheet { margin-top: 20px; }",
		".tui .sheet svg { background: #fff; border-radius: 4px; margin-bottom: 10px; display: block; max-width: 100%; height: auto; }",
		".tui .empty { color: #999; font-style: italic; }",
		/* overlay only */
		".tui-overlay { position: fixed; inset: 0; z-index: 10000; background: #000; overflow-y: auto; -webkit-overflow-scrolling: touch; }",
		".tui-overlay .tui { max-width: 900px; margin: 0 auto; padding: 16px 16px 60px 16px; }"
	].join("\n");

	function ensureStyle() {
		if (document.getElementById("transposeui-style")) return;
		var style = document.createElement("style");
		style.id = "transposeui-style";
		style.appendChild(document.createTextNode(CSS));
		document.head.appendChild(style);
	}

	function el(tag, className, html) {
		var node = document.createElement(tag);
		if (className) node.className = className;
		if (html != null) node.innerHTML = html;
		return node;
	}

	/* Builds the interface into `root` for `song`.
	   opts.onApply(songString) is called when the user applies instrument choices;
	   opts.onClose, when given, adds a button that calls it. */
	function mount(root, song, opts) {
		opts = opts || {};
		ensureStyle();
		root.classList.add("tui");
		root.innerHTML = "";

		root.appendChild(el("h1", null, "Transpose &amp; Sheet Music"));

		var info = el("div", "sub");
		var keyName = beepbox.Config.keys[song.key].name;
		info.innerHTML = "Concert <b>" + keyName + "</b> &middot; " + song.barCount +
			" measure" + (song.barCount === 1 ? "" : "s") + " &middot; " +
			song.beatsPerBar + " beats per measure &middot; " + song.tempo + " BPM";
		root.appendChild(info);

		root.appendChild(el("div", "sub", "Pick an instrument for each part. That swaps the sound <em>and</em> " +
			"writes the part at the pitch that player reads &mdash; concert B&#9837; shows as G for an alto sax."));

		var partsEl = el("div");
		root.appendChild(partsEl);

		// Each row picks what the part should be WRITTEN for. BeepBox songs are in
		// concert pitch, so "Keep current instrument" means leave it alone.
		var selects = [];
		for (var i = 0; i < song.getChannelCount(); i++) {
			if (song.getChannelIsNoise(i)) continue;
			var channel = song.channels[i];
			var noteCount = 0;
			for (var p = 0; p < channel.patterns.length; p++) noteCount += channel.patterns[p].notes.length;

			var row = el("div", "row");

			var sw = el("div", "swatch");
			sw.style.background = SheetMusic.channelColor(i);
			row.appendChild(sw);

			row.appendChild(el("div", "name", "<b>Channel " + (i + 1) + "</b><span>" + noteCount +
				" note" + (noteCount === 1 ? "" : "s") + "</span>"));

			var sel = document.createElement("select");
			var keep = document.createElement("option");
			keep.value = "-1";
			keep.textContent = "Keep current instrument";
			sel.appendChild(keep);
			for (var t = 0; t < INSTRUMENTS.length; t++) {
				var opt = document.createElement("option");
				opt.value = String(t);
				opt.textContent = INSTRUMENTS[t].name + (INSTRUMENTS[t].semitones ? "" : "  · concert");
				sel.appendChild(opt);
			}
			sel.value = "-1";
			row.appendChild(sel);
			selects.push({channelIndex: i, select: sel});

			partsEl.appendChild(row);
		}

		if (selects.length === 0) {
			partsEl.appendChild(el("div", "empty", "This song has no pitched channels to transpose."));
		}

		var bar = el("div", "bar");
		var generateButton = el("button", "primary");
		generateButton.type = "button";
		generateButton.textContent = "Generate Sheet Music";
		var applyButton = el("button");
		applyButton.type = "button";
		applyButton.textContent = "Apply instruments & open in editor";
		bar.appendChild(generateButton);
		bar.appendChild(applyButton);
		if (opts.onClose) {
			var closeButton = el("button");
			closeButton.type = "button";
			closeButton.textContent = "Back to editor";
			closeButton.addEventListener("click", opts.onClose);
			bar.appendChild(closeButton);
		}
		var status = el("span", "note");
		bar.appendChild(status);
		root.appendChild(bar);

		var sheet = el("div", "sheet");
		root.appendChild(sheet);

		function chosen(entry) {
			var idx = parseInt(entry.select.value, 10);
			return idx >= 0 ? INSTRUMENTS[idx] : null;
		}

		function regenerate() {
			sheet.innerHTML = "";
			var wrote = 0;
			for (var s = 0; s < selects.length; s++) {
				var out = SheetMusic.renderChannel(song, selects[s].channelIndex, chosen(selects[s]));
				if (out) { sheet.appendChild(out); wrote++; }
			}
			status.textContent = wrote === 0
				? "Nothing to write - no notes in this song yet."
				: "Wrote " + wrote + " part" + (wrote === 1 ? "" : "s") + ".";
		}

		generateButton.addEventListener("click", regenerate);

		// Redraw as soon as an instrument changes, so what is on screen always
		// matches the dropdowns rather than the last time Generate was pressed.
		for (var q = 0; q < selects.length; q++) {
			selects[q].select.addEventListener("change", function () {
				if (sheet.children.length) regenerate();
			});
		}

		// Swapping the instrument changes the song itself, so hand the edited song
		// back to the editor.
		applyButton.addEventListener("click", function () {
			var changed = 0;
			for (var s = 0; s < selects.length; s++) {
				var instrument = chosen(selects[s]);
				if (!instrument) continue;
				var channel = song.channels[selects[s].channelIndex];
				for (var k = 0; k < channel.instruments.length; k++) {
					channel.instruments[k].fromJsonObject(instrument.settings, false, 0);
					channel.instruments[k].preset = instrument.value;
				}
				changed++;
			}
			if (changed === 0) {
				status.textContent = "No instruments picked yet.";
				return;
			}
			if (opts.onApply) opts.onApply(song.toBase64String());
		});
	}

	/* Opens the interface on top of whatever page is already loaded. Used by the
	   offline single-file build, where there is no separate page to go to. */
	function openOverlay(song, opts) {
		opts = opts || {};
		ensureStyle();
		var overlay = el("div", "tui-overlay");
		var inner = el("div");
		overlay.appendChild(inner);

		function close() {
			if (overlay.parentNode) overlay.parentNode.removeChild(overlay);
			document.removeEventListener("keydown", onKey);
		}
		function onKey(event) { if (event.keyCode === 27) close(); }
		document.addEventListener("keydown", onKey);

		mount(inner, song, {
			onClose: close,
			onApply: opts.onApply || function (songString) {
				// The editor reads its song out of the hash on load, so the simplest
				// way to hand the edited song back is to reload onto it.
				window.location.hash = songString;
				window.location.reload();
			}
		});

		document.body.appendChild(overlay);
		overlay.scrollTop = 0;
		return close;
	}

	return {mount: mount, openOverlay: openOverlay};
}());
